pack_name = "ForgeBoys"
mc_version = "1.20.1"
modloader = "Forge"
default_providers = ["Modrinth"]
forbidden_mods = ["fabric-api"]

[mods.advanced-backups]
name = "advanced-backups"
version = "*"
server_side = true
client_side = true

[mods.ae2]
name = "ae2"
version = "*"

[mods.aether]
name = "aether"
version = "*"

[mods.alekiships]
name = "alekiships"
version = "*"

[mods.alekishipsbop]
name = "alekishipsbop"
version = "*"

[mods.alexs-caves]
name = "alexs-caves"
version = "*"

[mods.alternate-current]
name = "alternate-current"
version = "*"

[mods.appleskin]
name = "appleskin"
version = "*"

[mods.aquamirae]
name = "aquamirae"
version = "*"

[mods.attributes]
name = "attributes"
version = "*"

[mods.automobility]
name = "automobility"
version = "*"

[mods.bad-wither-no-cookie]
name = "bad-wither-no-cookie"
version = "*"

[mods.badoptimizations]
name = "badoptimizations"
version = "*"
server_side = false
client_side = true

[mods.better-archeology]
name = "better-archeology"
version = "*"

[mods.better-combat]
name = "better-combat"
version = "*"

[mods.better-third-person]
name = "better-third-person"
version = "*"

[mods.betterf3]
name = "betterf3"
version = "*"

[mods.biomes-o-plenty]
name = "biomes-o-plenty"
version = "*"

[mods.blue-skies]
name = "blue-skies"
version = "*"

[mods.botania]
name = "botania"
version = "*"

[mods.bridging-mod]
name = "bridging-mod"
version = "*"

[mods.canary]
name = "canary"
version = "*"

[mods.carry-on]
name = "carry-on"
version = "*"

[mods.chunky]
name = "chunky"
version = "*"
server_side = true
client_side = false

[mods.clean-tooltips]
name = "clean-tooltips"
version = "*"

[mods.cloth-config]
name = "cloth-config"
version = "*"

[mods.clumps]
name = "clumps"
version = "*"

[mods.connector-extras]
name = "connector-extras"
version = "*"

[mods.continents]
name = "continents"
version = "*"

[mods.continuity]
name = "continuity"
version = "*"
loader = "Fabric"

[mods.controlling]
name = "controlling"
version = "*"

[mods.copycats]
name = "copycats"
version = "*"

[mods.create]
name = "create"
version = "*"

[mods.create-diesel-generators]
name = "create-diesel-generators"
version = "*"

[mods.create-enchantment-industry]
name = "create-enchantment-industry"
version = "*"

[mods.create-new-age]
name = "create-new-age"
version = "*"

[mods.create-ore-excavation]
name = "create-ore-excavation"
version = "*"

[mods.create-steam-n-rails]
name = "create-steam-n-rails"
version = "*"

[mods.create-wizardry]
name = "create-wizardry"
version = "*"

[mods.createaddition]
name = "createaddition"
version = "*"

[mods.cristel-lib]
name = "cristel-lib"
version = "*"
providers = ["Raw"]
download_url = "https://cdn.modrinth.com/data/cl223EMc/versions/amI1oyGG/cristellib-1.1.5-forge.jar"
server_side = true
client_side = false

[mods.ct-overhaul-village]
name = "ct-overhaul-village"
version = "*"

[mods.curious-lanterns]
name = "curious-lanterns"
version = "*"
providers = ["Raw"]
download_url = "https://mediafilez.forgecdn.net/files/5245/133/curiouslanterns-1.20.1-1.3.2.jar"

[mods.deeperdarker]
name = "deeperdarker"
version = "*"

[mods.disable-elytra]
name = "disable-elytra"
version = "*"
loader = "Fabric"

[mods.dungeon-now-loading]
name = "dungeon-now-loading"
version = "*"

[mods.embeddium]
name = "embeddium"
version = "*"

[mods.emi]
name = "emi"
version = "*"
server_side = true
client_side = true

[mods.emi-loot]
name = "emi-loot"
version = "*"

[mods.emi-ores]
name = "emi-ores"
version = "*"
loader = "Fabric"

[mods.emienchants]
name = "emienchants"
version = "*"

[mods.emiffect]
name = "emiffect"
version = "*"

[mods.emitrades]
name = "emitrades"
version = "*"

[mods.enderio]
name = "enderio"
version = "*"

[mods.entityculling]
name = "entityculling"
version = "*"

[mods.extraalchemy]
name = "extraalchemy"
version = "*"
loader = "Fabric"

[mods.farmers-delight]
name = "farmers-delight"
version = "*"

[mods.ferrite-core]
name = "ferrite-core"
version = "*"

[mods.fish-of-thieves]
name = "fish-of-thieves"
version = "*"

[mods.fish-tanks]
name = "fish-tanks"
version = "*"

[mods.gamemenumodoption]
name = "gamemenumodoption"
version = "*"

[mods.gliders]
name = "gliders"
version = "*"

[mods.gravestone-mod]
name = "gravestone-mod"
version = "*"

[mods.hardcore-revival]
name = "hardcore-revival"
version = "*"

[mods.ice-and-fire-dragons]
name = "ice-and-fire-dragons"
version = "*"

[mods.immediatelyfast]
name = "immediatelyfast"
version = "*"
server_side = false
client_side = true

[mods.immersive-aircraft]
name = "immersive-aircraft"
version = "*"

[mods.immersive-melodies]
name = "immersive-melodies"
version = "*"

[mods.incendium]
name = "incendium"
version = "*"

[mods.invmove]
name = "invmove"
version = "*"

[mods.iris-flw-compat]
name = "iris-flw-compat"
version = "*"

[mods.irons-spells-n-spellbooks]
name = "irons-spells-n-spellbooks"
version = "*"

[mods.jade]
name = "jade"
version = "*"

[mods.jei]
name = "jei"
version = "*"
server_side = true
client_side = true

[mods.l_enders-cataclysm]
name = "l_enders-cataclysm"
version = "*"

[mods.leaves-be-gone]
name = "leaves-be-gone"
version = "*"

[mods.lesraisins-weapon]
name = "lesraisins-weapon"
version = "*"

[mods.littletiles]
name = "littletiles"
version = "*"

[mods.lucent]
name = "lucent"
version = "*"
server_side = false
client_side = true

[mods.man-of-many-planes]
name = "man-of-many-planes"
version = "*"

[mods.memoryleakfix]
name = "memoryleakfix"
version = "*"

[mods.mobtimizations]
name = "mobtimizations"
version = "*"

[mods.modernfix]
name = "modernfix"
version = "*"
server_side = true
client_side = true

[mods.mouse-tweaks]
name = "mouse-tweaks"
version = "*"

[mods.mowzies-mobs]
name = "mowzies-mobs"
version = "*"
providers = ["Raw"]
download_url = "https://mediafilez.forgecdn.net/files/5399/941/mowziesmobs-1.6.5.jar"

[mods.mutant-monsters]
name = "mutant-monsters"
version = "*"

[mods.mythic-mounts]
name = "mythic-mounts"
version = "*"

[mods.natures-compass]
name = "natures-compass"
version = "*"

[mods.noisium]
name = "noisium"
version = "*"

[mods.oceans-delight]
name = "oceans-delight"
version = "*"

[mods.oculus]
name = "oculus"
version = "*"

[mods.paladins-and-priests]
name = "paladins-and-priests"
version = "*"
loader = "Fabric"

[mods.patchouli]
name = "patchouli"
version = "*"

[mods.pehkui]
name = "pehkui"
version = "*"

[mods.ping-wheel]
name = "ping-wheel"
version = "*"

[mods.pizzacraft]
name = "pizzacraft"
version = "*"

[mods.polymorph]
name = "polymorph"
version = "*"

[mods.precise-manufacturing]
name = "precise-manufacturing"
version = "*"

[mods.radiant-gear]
name = "radiant-gear"
version = "*"
server_side = true
client_side = true

[mods.rats]
name = "rats"
version = "*"

[mods.rubidium-extra]
name = "rubidium-extra"
version = "*"

[mods.servercore]
name = "servercore"
version = "*"

[mods.simple-discord-rpc]
name = "simple-discord-rpc"
version = "*"

[mods.simply-skills]
name = "simply-skills"
version = "*"
loader = "Fabric"

[mods.skills]
name = "skills"
version = "*"

[mods.slice-and-dice]
name = "slice-and-dice"
version = "*"

[mods.sound]
name = "sound"
version = "*"

[mods.spark]
name = "spark"
version = "*"

[mods.spectrum]
name = "spectrum"
version = "1.7.15"
loader = "Fabric"

[mods.stardew-fishing]
name = "stardew-fishing"
version = "*"

[mods.stellarity]
name = "stellarity"
version = "*"

[mods.timeless-and-classics-zero]
name = "timeless-and-classics-zero"
version = "*"

[mods.towns-and-towers]
name = "towns-and-towers"
version = "*"

[mods.trade-cycling]
name = "trade-cycling"
version = "*"

[mods.travelers-titles]
name = "travelers-titles"
version = "*"

[mods.travelersbackpack]
name = "travelersbackpack"
version = "*"

[mods.truly-modular-archery]
name = "truly-modular-archery"
version = "*"

[mods.truly-modular-armory]
name = "truly-modular-armory"
version = "*"

[mods.truly-modular-arsenal]
name = "truly-modular-arsenal"
version = "*"

[mods.upgrade-aquatic]
name = "upgrade-aquatic"
version = "*"

[mods.when-dungeons-arise]
name = "when-dungeons-arise"
version = "*"

[mods.when-dungeons-arise-seven-seas]
name = "when-dungeons-arise-seven-seas"
version = "*"

[mods.xaeros-minimap]
name = "xaeros-minimap"
version = "*"

[mods.xaeros-world-map]
name = "xaeros-world-map"
version = "*"

[files."./client/config/xaerominimap.txt"]
target_path = "config/xaerominimap.txt"
side = "Client"
apply_policy = "Once"

[files."./client/options.txt"]
target_path = "options.txt"
side = "Client"
apply_policy = "Once"

[files."./client/servers.dat"]
target_path = "servers.dat"
side = "Client"
apply_policy = "Always"

[files."./server/config/AdvancedBackups.properties"]
target_path = "config/AdvancedBackups.properties"
side = "Server"
apply_policy = "Always"

[files."./server/config/carryon-common.toml"]
target_path = "config/carryon-common.toml"
side = "Server"
apply_policy = "Always"

[files."./server/config/iceandfire-common.toml"]
target_path = "config/iceandfire-common.toml"
side = "Server"
apply_policy = "Always"

[files."./server/config/rats-common.toml"]
target_path = "config/rats-common.toml"
side = "Server"
apply_policy = "Always"

[files."./server/server.properties"]
target_path = "server.properties"
side = "Server"
apply_policy = "Always"

[files."./server/whitelist.json"]
target_path = "whitelist.json"
side = "Server"
apply_policy = "Always"
