pack_name = "ForgeBoys"
mc_version = "1.20.1"
modloader = "Forge"
default_providers = ["Modrinth"]
forbidden_mods = ["fabric-api"]

[mods.ae2]
name = "ae2"
version = "*"

[mods.aether]
name = "aether"
version = "*"

[mods.alexs-caves]
name = "alexs-caves"
version = "*"

[mods.alternate-current]
name = "alternate-current"
version = "*"

[mods.appleskin]
name = "appleskin"
version = "*"

[mods.automobility]
name = "automobility"
version = "*"

[mods.bad-wither-no-cookie]
name = "bad-wither-no-cookie"
version = "*"

[mods.better-archeology]
name = "better-archeology"
version = "*"

[mods.better-combat]
name = "better-combat"
version = "*"

[mods.betterf3]
name = "betterf3"
version = "*"

[mods.biomes-o-plenty]
name = "biomes-o-plenty"
version = "*"

[mods.blue-skies]
name = "blue-skies"
version = "*"

[mods.botania]
name = "botania"
version = "*"

[mods.canary]
name = "canary"
version = "*"

[mods.carry-on]
name = "carry-on"
version = "*"

[mods.chunky]
name = "chunky"
version = "*"
server_side = true
client_side = false

[mods.cloth-config]
name = "cloth-config"
version = "*"

[mods.clumps]
name = "clumps"
version = "*"

[mods.connector-extras]
name = "connector-extras"
version = "*"

[mods.continuity]
name = "continuity"
version = "*"
loader = "Fabric"

[mods.controlling]
name = "controlling"
version = "*"

[mods.copycats]
name = "copycats"
version = "*"

[mods.create]
name = "create"
version = "*"

[mods.create-diesel-generators]
name = "create-diesel-generators"
version = "*"

[mods.create-enchantment-industry]
name = "create-enchantment-industry"
version = "*"

[mods.create-new-age]
name = "create-new-age"
version = "*"

[mods.create-ore-excavation]
name = "create-ore-excavation"
version = "*"

[mods.create-steam-n-rails]
name = "create-steam-n-rails"
version = "*"

[mods.create-structures]
name = "create-structures"
version = "*"

[mods.create-wizardry]
name = "create-wizardry"
version = "*"

[mods.createaddition]
name = "createaddition"
version = "*"

[mods.cristel-lib]
name = "cristel-lib"
version = "*"
providers = ["Raw"]
download_url = "https://cdn.modrinth.com/data/cl223EMc/versions/amI1oyGG/cristellib-1.1.5-forge.jar"
server_side = true
client_side = false

[mods.ct-overhaul-village]
name = "ct-overhaul-village"
version = "*"

[mods.ctov-create-structures]
name = "ctov-create-structures"
version = "*"

[mods.curious-lanterns]
name = "curious-lanterns"
version = "*"
providers = ["Raw"]
download_url = "https://mediafilez.forgecdn.net/files/5245/133/curiouslanterns-1.20.1-1.3.2.jar"

[mods.deeperdarker]
name = "deeperdarker"
version = "*"

[mods.dungeon-now-loading]
name = "dungeon-now-loading"
version = "*"

[mods.embeddium]
name = "embeddium"
version = "*"

[mods.emi]
name = "emi"
version = "*"
server_side = true
client_side = true

[mods.emi-loot]
name = "emi-loot"
version = "*"

[mods.emienchants]
name = "emienchants"
version = "*"

[mods.emiffect]
name = "emiffect"
version = "*"

[mods.emitrades]
name = "emitrades"
version = "*"

[mods.enderio]
name = "enderio"
version = "*"

[mods.entityculling]
name = "entityculling"
version = "*"

[mods.farmers-delight]
name = "farmers-delight"
version = "*"

[mods.fastback]
name = "fastback"
version = "*"
providers = ["Raw"]
download_url = "https://cdn.modrinth.com/data/ZHKrK8Rp/versions/sCxHMib4/fastback-0.15.6%2B1.20.1-forge.jar"
server_side = true
client_side = false

[mods.ferrite-core]
name = "ferrite-core"
version = "*"

[mods.gamemenumodoption]
name = "gamemenumodoption"
version = "*"

[mods.gliders]
name = "gliders"
version = "*"

[mods.gravestone-mod]
name = "gravestone-mod"
version = "*"

[mods.hardcore-revival]
name = "hardcore-revival"
version = "*"

[mods.ice-and-fire-dragons]
name = "ice-and-fire-dragons"
version = "*"

[mods.immersive-aircraft]
name = "immersive-aircraft"
version = "*"

[mods.immersive-melodies]
name = "immersive-melodies"
version = "*"

[mods.invmove]
name = "invmove"
version = "*"

[mods.iris-flw-compat]
name = "iris-flw-compat"
version = "*"

[mods.irons-spells-n-spellbooks]
name = "irons-spells-n-spellbooks"
version = "*"

[mods.jade]
name = "jade"
version = "*"

[mods.l_enders-cataclysm]
name = "l_enders-cataclysm"
version = "*"

[mods.leaves-be-gone]
name = "leaves-be-gone"
version = "*"

[mods.man-of-many-planes]
name = "man-of-many-planes"
version = "*"

[mods.medieval-origins-revival]
name = "medieval-origins-revival"
version = "*"

[mods.memoryleakfix]
name = "memoryleakfix"
version = "*"

[mods.mouse-tweaks]
name = "mouse-tweaks"
version = "*"

[mods.mowzies-mobs]
name = "mowzies-mobs"
version = "*"
providers = ["Raw"]
download_url = "https://mediafilez.forgecdn.net/files/5399/941/mowziesmobs-1.6.5.jar"

[mods.mutant-monsters]
name = "mutant-monsters"
version = "*"

[mods.natures-compass]
name = "natures-compass"
version = "*"

[mods.noisium]
name = "noisium"
version = "*"

[mods.oculus]
name = "oculus"
version = "*"

[mods.origins-forge]
name = "origins-forge"
version = "*"

[mods.patchouli]
name = "patchouli"
version = "*"

[mods.pizzacraft]
name = "pizzacraft"
version = "*"

[mods.polymorph]
name = "polymorph"
version = "*"

[mods.radiant-gear]
name = "radiant-gear"
version = "*"
server_side = true
client_side = true

[mods.rats]
name = "rats"
version = "*"

[mods.rubidium-extra]
name = "rubidium-extra"
version = "*"

[mods.servercore]
name = "servercore"
version = "*"

[mods.slice-and-dice]
name = "slice-and-dice"
version = "*"

[mods.spark]
name = "spark"
version = "*"

[mods.spectrum]
name = "spectrum"
version = "1.7.15"
loader = "Fabric"

[mods.timeless-and-classics-zero]
name = "timeless-and-classics-zero"
version = "*"

[mods.towns-and-towers]
name = "towns-and-towers"
version = "*"

[mods.travelersbackpack]
name = "travelersbackpack"
version = "*"

[mods.truly-modular-archery]
name = "truly-modular-archery"
version = "*"

[mods.truly-modular-armory]
name = "truly-modular-armory"
version = "*"

[mods.truly-modular-arsenal]
name = "truly-modular-arsenal"
version = "*"

[mods.when-dungeons-arise]
name = "when-dungeons-arise"
version = "*"

[mods.xaeros-minimap]
name = "xaeros-minimap"
version = "*"

[mods.xaeros-world-map]
name = "xaeros-world-map"
version = "*"

[files."./client/options.txt"]
target_path = "options.txt"
side = "Client"
apply_policy = "Once"

[files."./client/servers.dat"]
target_path = "servers.dat"
side = "Client"
apply_policy = "Always"

[files."./server/whitelist.json"]
target_path = "whitelist.json"
side = "Server"
apply_policy = "Always"
