pack_name = "ForgeBoys"
mc_version = "1.20.1"
modloader = "Forge"
default_providers = ["Modrinth"]
forbidden_mods = ["fabric-api"]

[mods.icarus]
name = "icarus"
version = "*"

[mods.jade]
name = "jade"
version = "*"

[mods.medieval-origins-revival]
name = "medieval-origins-revival"
version = "*"

[mods.aether]
name = "aether"
version = "*"

[mods.copycats]
name = "copycats"
version = "*"

[mods.torcherino]
name = "torcherino"
version = "*"

[mods.origins-forge]
name = "origins-forge"
version = "*"

[mods.clumps]
name = "clumps"
version = "*"

[mods.create]
name = "create"
version = "*"

[mods.alexs-caves]
name = "alexs-caves"
version = "*"

[mods.connector-extras]
name = "connector-extras"
version = "*"

[mods.carry-on]
name = "carry-on"
version = "*"

[mods.ice-and-fire-dragons]
name = "ice-and-fire-dragons"
version = "*"

[mods.emi]
name = "emi"
version = "*"

[mods.alternate-current]
name = "alternate-current"
version = "*"

[mods.betterf3]
name = "betterf3"
version = "*"
